# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc086be3d936b55f008c5be38161244fae2629ec6e7dc10fa63c23f8779db0345df7fd7ec03a9e8877c8c78c11c79b58b8a3e801da96d6629b0fe9bd4348f293

test:
  secret_key_base: b84ea6856d3d1fd1095b07d2cb45f82637b8c8f9f670803ec839c46d9560a75a262730c94751146265265f05604c1ab65cd6ea91ab0f206ed88514b3ae99525a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
