# A particular version of a Schematron document used to check FindingAids for Issues
#
# Generated by XML processing of a schematron file
class Schematron < ActiveRecord::Base
  has_many :issues
  has_many :runs
end
