# A particular version of a Schematron document used to check FindingAids for Issues
#
# Generated by XML processing of a schematron file
class Schematron < ActiveRecord::Base
  has_many :issues
  has_many :runs

  validates :digest, presence: true, length: {is: 64}, format: /[a-zA-Z0-9]+/
  validates_each :digest do |record, attr, value|
    record.errors.add(attr, "must be associated with an extant SchematronFile") unless record.file
  end

  # @return [SchematronFile] the SchematronFile associated with this record
  def file
    SchematronFile[digest]
  end
end
