# A particular version of a Schematron document used to check FindingAids for Issues
#
# Generated by XML processing of a schematron file
class Schematron < ActiveRecord::Base
  has_many :issues, dependent: :destroy
  has_many :runs
  accepts_nested_attributes_for :issues

  after_destroy :delete_file

  validates :digest, presence: true, length: {is: 64}, format: /[a-zA-Z0-9]+/
  validates_each :digest do |record, attr, value|
    record.errors.add(attr, "must be associated with an extant SchematronFile") unless record.file.is_a? SchematronFile
  end

  # @return [SchematronFile] the SchematronFile associated with this record
  def file
    SchematronFile[digest]
  end

  private
  # Callback to delete related SchematronFile
  def delete_file
    File.unlink file
  end
end
